spring:
  datasource:
    url:jdbc:h2:mem: testdb
    driverClassName: org.h2.Driver
    username: sa
    password: pass
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

game:
  url: http://localhost:8080/games/{id}
  players: 2
  pits: 14
  initial-stones-per-pit: 6
  non-house-pit-per-player: 6


